# Generated by Django 3.1.7 on 2021-03-17 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_alberto', models.CharField(max_length=50)),
                ('visitas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LasHoras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_acceso', models.DateTimeField()),
                ('grupete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSeguWeb.grupete')),
            ],
        ),
    ]
