# Generated by Django 3.1.7 on 2021-03-17 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSeguWeb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupete',
            old_name='id_alberto',
            new_name='id_grupete',
        ),
    ]
